model: PFCN_DMF

dataset: ml-1M
field_separator: "\t"
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
LABEL_FIELD: label

load_col:
  inter: [user_id, item_id, label]
  user: [user_id, gender]

embedding_size: 64
sst_attr_list: ['gender']
filter_mode: cm
num_layers: 2
mlp_dropout: 0.2
mlp_activation: leakyrelu
dis_activation: leakyrelu
dis_dropout: 0.2
dis_weight: 1000.0
dis_hidden_size_list: [64, 32]

epochs: 100
learning_rate: 0.001
train_batch_size: 512
eval_batch_size: 8192
weight_decay: 0.0001
stopping_step: 10

eval_args:
  split: {'RS': [8, 1, 1]}
  group_by: user
  order: RO
  mode: uni100
metrics: [
  "NDCG", "Recall", "Hit", "MRR", "Precision", "MAP",
  "DifferentialFairness", "ValueUnfairness", "NonParityUnfairness",
  "ItemCoverage", "ShannonEntropy"
]
valid_metric: NDCG@5
topk: [5, 10, 20, 50]
popularity_ratio: 0.1
